name: CI-CD-Pipeline

on:
  pull_request:
    branches: [ "main" ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

  Install-dependencies:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Install dependencies
      run: echo "install dependencies"
  setup-java:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Set up Java
      run: echo "java"

  build-maven:
    runs-on: ubuntu-latest
    needs: setup-java
    steps:
    - name: Build with Maven
      run: echo "Maven Build completed"

  sonar-scan:
    runs-on: ubuntu-latest
    needs: build-maven
    steps:
    - name: SonarQube Scan
      run: echo "SonarSource"

  snyk-scan:
    runs-on: ubuntu-latest
    needs: sonar-scan
    steps:
    - name: Snyk Scan
      run: echo "snyk"

  upload-artifactory:
    runs-on: ubuntu-latest
    needs: snyk-scan
    steps:
    - name: Upload to Artifactory
      run: echo "mvn deploy"

  deploy-eks:
    runs-on: ubuntu-latest
    needs: upload-artifactory
    steps:
    - name: Deploy to EKS Cluster (Via ArgoCD)
      run: echo "Deployment to EKS"

  deploy-qa:
    runs-on: ubuntu-latest
    needs: deploy-eks
    steps:
    - name: Deploy to QA
      run: echo "Deploy to QA"
      
  smoke-test:
    runs-on: ubuntu-latest
    steps:
    - name: Post-PRD Smoke Test
      run: echo "Post-PRD smoke test"
